
name: Build & Release ZIP

on:
  workflow_dispatch:   # يدوي فقط
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload dist as artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

      - name: ZIP dist
        run: cd dist && zip -r ../dist.zip .

      - name: Upload ZIP to Release
        uses: ncipollo/release-action@v1
        with:
          tag: v1.0.3
          name: Build v1.0.3
          artifacts: "dist.zip"
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
